dist: bionic
language: python
python:
  - "3.8"
before_install:
  - python --version
  - pip install -U pip
  - pip install -r requirements.txt
install:
  - pip install ".[test]" .
script: pipenv run pytest --verbose --color=yes
after_success:
  - pipenv run coverage run -m pytest --verbose --color=yes
  - pipenv run coverage report -m --include="letsdebughelper/*"
  - codecov
