dist: bionic
language: python
python:
  - "3.8"
before_install:
  - pip install --upgrade pip
install:
  - pip install pipenv pytest
script:
  - pipenv run coverage run -m pytest --verbose --color=yes
  - pipenv run coverage report -m --include="letsdebughelper/*"
