dist: jammy
language: python
python:
  - "3.9"
  - "3.10"
before_install:
  - python --version
  - pip install -U pip
  - pip install poetry
install:
  - poetry install
script:
  - poetry run flake8 --verbose letsdebughelper
  - poetry run pytest --cov-report term-missing:skip-covered --cov=letsdebughelper --verbose --color=yes letsdebughelper
after_success:
  - poetry run pytest --cov-report term-missing:skip-covered --cov=letsdebughelper --verbose --color=yes letsdebughelper
  - poetry run pipenv run coveralls
