name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12" ]
        os: [ ubuntu-22.04, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Env Setup
        env:
          PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
        run: make setup

      - name: Check Env
        run: make check_env

      - name: Lint
        run: make lint

      - name: Typing
        run: make typing

      - name: Test and Coverage
        run: make coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Package
        run: WHL_VERSION=prerelease make package

      - name: Test Package Installation
        run: pip3 install dist/*.whl

      - name: Test Scripts
        run: |
          lets-debug --help
