name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docker
        run: make docker_build

      - name: Check Env
        run: make docker_check_env

      - name: Lint
        run: make docker_lint

      - name: Test and Coverage
        run: make docker_coverage

      - name: Package
        run: WHL_VERSION=prerelease make docker_package

      - name: Test Package Installation
        run: pip3 install dist/*.whl

      - name: Test Scripts
        run: |
          lets-debug --help
