name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          pip install -U pip
          pip install poetry

      - name: Env Setup
        env:
          PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
        run: make setup

      - name: Check Env
        run: make check_env

      - name: Lint
        run: make lint

      - name: Test and Coverage
        run: make coverage

      - name: Package
        run: WHL_VERSION=prerelease make package

      - name: Test Package Installation
        run: pip3 install dist/*.whl

      - name: Test Scripts
        run: |
          lets-debug --help
